{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\ntestallur_demo.py:19: Exception"}, "start": 1624886391469, "stop": 1624886391470, "uuid": "e67c9b86-efc5-4c94-9fca-f41467be589b", "historyId": "8c51ccd237f7900b73fb9defe049a61b", "testCaseId": "50dd88b2b335ebae88be4ca285e78581", "fullName": "testallur_demo#test_broken", "labels": [{"name": "suite", "value": "testallur_demo"}, {"name": "host", "value": "LAPTOP-59S4SB4A"}, {"name": "thread", "value": "22296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testallur_demo"}]}